services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: wikidocify_db    # Database name (should match DB_NAME in your Go app)
      POSTGRES_USER: username       # Ensure this matches the DB_USER in your Go app
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d wikidocify_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  web:
    image: my-go-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_NAME: wikidocify_db      
      DB_USER: username          
      DB_PASSWORD: password        
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
