version: '3.9'

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wikidocify_db
    ports:
      - "5432:5432"
    restart: always