POST http://localhost:8080/documents

{
    "ID": "1" 
	"Title": "first doc"   
	"Author": "first Author" 
	"Content": "first Content"   
	"CreatedAt": 1566454995.8361387
	"UpdatedAt": 1566454995.8361387
}
